name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  apple_maps_flutter:
    git:
      url: https://github.com/pastordee/apple_maps_flutter.git
      ref: master
  google_maps_flutter: ^2.6.1
  google_maps_flutter_platform_interface: ^2.6.0
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # pedantic: ^1.11.0
